FROM mcr.microsoft.com/java/jdk:8u202-zulu-centos
MAINTAINER hzf "hzf@centit.com"
ADD target/*.jar /home/eureka-server.jar
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod 777 /wait-for-it.sh
CMD ["java","-jar","/home/eureka-server.jar"]
