server:
  port: 10081
  servlet: # 添加统一服务前缀
      context-path: /framework

spring:
  #application:
    #name: FRAMEWORK-SERVICE
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.131.61:8847,192.168.131.61:8848,192.168.131.61:8849   # nacos discovery地址
        #ip: 192.168.137.49
        #namespace: e100081f-de9c-4b52-8051-11346913b8af

  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.134.6:3308/framework?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://192.168.131.43:3306/zb_sysmgr?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    dbcp2:
      max-wait-millis: 10000
      max-idle: 15
      initial-size: 10
      validation-query: SELECT 1
      connection-properties: characterEncoding=utf8

#用户目录
userdirectory:
  default:
    rank: YG
    station: ZY
    rolecode: G-SYSADMIN
  ldap:
    url: LDAP://192.168.128.5:389
    username: accounts@centit.com
    userpassword: yhs@yhs1
    searchbase: CN=Users,DC=centit,DC=com

#系统属性
app:
  home: /D/Projects/RunData/ip_home
  support:
    tenant: true
#业务配置信息
opt:
  name: 框架测试项目
  subsystem: false

jdbc:
  url:
#单点登录相关配置信息
cas:
  sso: false
  home: https://zou_wy:8443/centit-cas
#登录成功后的首页
local:
  home: http://zouwuyangpc:8084/product-ip
  firstpage: /system/mainframe/index

#是否开放实施人员入口
deploy:
  enabled: true
#框架相关的表主键生成规制， 目前关联的就是 userinfo 和 uintinfo 两个表
#default value {"prefix":"U","length":8,"pad":"0"}
framework:
  userinfo:
    id:
      generator: default
#default value {"prefix":"D","length":6,"pad":"0"}
  unitinfo:
    id:
      generator: default
  roleinfo:
    id:
      generator: default
#多国语言设置
sys:
  multi_lang: true
  defalut_lang: zh_CN

session:
    redis:
      host: 192.168.137.49
      port: 6379
