server:
  port: 10088

spring:
  application:
    name: GATEWAY-SERVICE
  redis:
    host: 192.168.134.9
    port: 6379
  security:
    oauth2:
      client:
        client-id: 100001
        client-secret: 100001abcdefg
        grant-type: authorization_code
#        authorization-uri: http://codefanpc:8088/cas/oauth2.0/authorize
#        access-token-uri: http://codefanpc:8088/cas/oauth2.0/accessToken
#        user-info-uri: http://codefanpc:8088/cas/oauth2.0/profile
        authorization-uri: http://localhost:8080/cas/oauth2.0/authorize
        access-token-uri: http://localhost:8080/cas/oauth2.0/accessToken
        user-info-uri: http://localhost:8080/cas/oauth2.0/profile
        redirect-uri: http://localhost:10088/frame/callback
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' # 配置RSA的公钥访问地址
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.137.49:8847,192.168.137.49:8848,192.168.137.49:8849   # nacos discovery地址
        #server-addr: 192.168.131.61:8847,192.168.131.61:8848,192.168.131.61:8849   #开发服务器地址
        server-addr: localhost:8847,localhost:8848,localhost:8849
        #ip: 192.168.137.49
        #namespace: d0e7c836-f1a3-4586-936b-9b7da8ce5471
    gateway:
      enabled: true                 #开启网关  false 关闭网关  开启以服务中心id去注册中心上获取转发地址
      routes:                        #路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
      - id: path_route_20210317a
        uri: https://www.baidu.com
        predicates:
        - Query=url,baidu

      - id: oauth2-resource-route
        uri: lb://oauth2-resource
        predicates:
        - Path=/resource/**
        filters:
        - StripPrefix=1

      - id: oauth2-auth-route
        uri: lb://oauth2-auth
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1

      - id: oauth2-auth-token
        uri: lb://oauth2-auth
        predicates:
        - Path=/oauth/token
        filters:
        - PreserveHostHeader

      - id: CAS-SERVICE-ROUTE
        uri: lb://CAS-SERVICE
        predicates:
        - Path=/cas/**

      - id: FRAMEWORK-SERVICE         # 当前路由的标识, 要求唯一
        uri: lb://FRAMEWORK-SERVICE   # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
        predicates:                  # 断言(就是路由转发要满足的条件)
        - Path=/framework/**              # 当请求路径满足Path指定的规则时,才进行路由转发
        #filters:                     # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
        #- StripPrefix=1              # 转发之前去掉1层路径
        #- RewritePath=/api/(?<segment>/?.*), /$\{segment}
        #- Cookie=chocolate, ch.p     # cookie named chocolate whose value matches the ch.p
        #- Header=X-Request-Id, \d+    # has a header named X-Request-Id

  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.134.6:3308/framework?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://127.0.0.1:3306/framework?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://192.168.131.43:3306/zb_sysmgr?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    dbcp2:
      max-wait-millis: 10000
      max-idle: 15
      initial-size: 10
      validation-query: SELECT 1
      connection-properties: characterEncoding=utf8

secure:
  ignore:
    urls: # 配置白名单路径
    - "/frame/login"
    - "/frame/callback"
    - "/frame/userinfo"
    - "/frame/logout"
    - "/cas/login"
    - "/cas/oauth2.0/authorize"
    - "/cas/oauth2.0/accessToken"
    - "/cas/oauth2.0/profile"
    - "/cas/**"

http:
  csrf:
    enable: false
  filter:
    chain:
      continueBeforeSuccessfulAuthentication: false

#框架相关的表主键生成规制， 目前关联的就是 userinfo 和 uintinfo 两个表
#default value {"prefix":"U","length":8,"pad":"0"}
framework:
  userinfo:
    id:
      generator: default
#default value {"prefix":"D","length":6,"pad":"0"}
  unitinfo:
    id:
      generator: default
  roleinfo:
    id:
      generator: default

session:
  redis:
    host: 192.168.134.9
    port: 6379

security:
  login:
    cas:
      enabled: true
      localHome: http://localhost:10088
      casHome: http://localhost:8080/cas
  http:
    csrf-enable: false
    filter-continue-authentication: false
    x-frame-options-mode: deny
#系统属性
app:
  support:
    tenant: true
